name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lesson 1 - Functions
      id: lesson-1-functions
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 2
        setup-command: sudo -H pip3 install pytest timeout_decorator pytest-mock
    - name: Exercise 1
      id: exercise-1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 3
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LESSON-1-FUNCTIONS_RESULTS: "${{steps.lesson-1-functions.outputs.result}}"
        EXERCISE-1_RESULTS: "${{steps.exercise-1.outputs.result}}"
      with:
        runners: lesson-1-functions,exercise-1
